schoolmanagement/academics/urls.py
from .views import academics_index, add_school_year, view_school_year, list_school_year, \
    add_grade_level, view_grade_level, list_grade_levels, add_subject, view_subject, list_subjects
from django.urls import path


app_name = 'academics'

urlpatterns = [
    path('', academics_index, name='academics_index'),

    # path('add_instructor/', add_instructor, name='add_instructor'),
    # path('instructor/login/', instructor_login, name='instructor_login'),
    # path('instructor/<int:instructor_id>/', instructor_detail, name='instructor_detail'),
    # path('instructor/logout/', instructor_logout, name='instructor_logout'),

    path('add_school_year/', add_school_year, name='add_school_year'),
    path('view_school_year/<int:school_year_id>/', view_school_year, name='view_school_year'),
    path('list_school_year/', list_school_year, name='list_school_year'),

    path('add_grade_level/', add_grade_level, name='add_grade_level'),
    path('view_grade_level/<int:grade_level_id>/', view_grade_level, name='view_grade_level'),
    path('list_grade_levels/', list_grade_levels, name='list_grade_levels'),

    path('add_subject/', add_subject, name='add_subject'),
    path('view_subject/<int:subject_id>/', view_subject, name='view_subject'),
    path('list_subjects/', list_subjects, name='list_subjects'),

]

schoolmanagement/schoolmanagement/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('students/', include('students.urls')),
    path('webutil/', include('webutil.urls')),
    path('academics/', include('academics.urls')),
    path('enrollment/', include('enrollment.urls')),
    path('instructors/', include('instructors.urls')),
]

schoolmanagement/webutil/urls.py
from django.urls import path
from .views import index

app_name = 'webutil'

urlpatterns = [
    path('', index, name='index-webutil'),

]

schoolmanagement/academics/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _


# # Instructor Model
# class Instructor(models.Model):
#     user = models.OneToOneField(User, on_delete=models.CASCADE)
#     title = models.CharField(max_length=100) # e.g., Dr., Mr., Ms.
#     department = models.CharField(max_length=100)

#     def __str__(self):
#         user: User = self.user  # Type hint for IDE
#         return f"{self.title} {self.user.first_name} {self.user.last_name}"

class SchoolYear(models.Model):
    name = models.CharField(max_length=100, verbose_name=_("Name"), blank=True)
    start_date = models.DateField(verbose_name=_("Start Date"))
    end_date = models.DateField(verbose_name=_("End Date"))
    is_current = models.BooleanField(default=False, verbose_name=_("Is Current School Year"))

    class Meta:
        verbose_name = _("School Year")
        verbose_name_plural = _("School Years")
        ordering = ['-start_date']  # Orders the school years starting with the most recent

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if self.is_current:
            # Ensure that there is only one current school year
            SchoolYear.objects.filter(is_current=True).update(is_current=False)
        super(SchoolYear, self).save(*args, **kwargs)


class GradeLevel(models.Model):
    name = models.CharField(_("Grade Level"), max_length=50, blank=True)
    school_year = models.ForeignKey(
        SchoolYear, 
        on_delete=models.CASCADE, 
        verbose_name=_("School Year"), 
        related_name='grade_levels'
    )

    class Meta:
        verbose_name = _("Grade Level")
        verbose_name_plural = _("Grade Levels")
        ordering = ['name']
        unique_together = ['name', 'school_year']

    def __str__(self):
        return f"{self.name} - {self.school_year.name}"


class Subject(models.Model):
    name = models.CharField(_("Subject Name"), max_length=255, blank=True)
    code = models.CharField(_("Subject Code"), max_length=10, unique=True)
    grade_level = models.ForeignKey(
        GradeLevel, 
        on_delete=models.CASCADE, 
        verbose_name=_("Grade Level"), 
        related_name='subjects'
    )
    description = models.TextField(_("Description"), blank=True)

    class Meta:
        verbose_name = _("Subject")
        verbose_name_plural = _("Subjects")
        ordering = ['name']

    def __str__(self):
        return f"{self.name} ({self.code}) - {self.grade_level.name}"


# # Class Model
# class Classroom(models.Model):
#     subject = models.ForeignKey(Subject, on_delete=models.CASCADE)
#     instructor = models.ForeignKey(Instructor, on_delete=models.CASCADE)
#     grade_level = models.ForeignKey(GradeLevel, on_delete=models.CASCADE, null=True, blank=True)
#     strand = models.ForeignKey(Strand, on_delete=models.CASCADE, null=True, blank=True)
#     schedule = models.CharField(max_length=100) # This can be improved with a more complex schedule model

#     def __str__(self):
#         return f"{self.subject.name} - {self.instructor.user.last_name}"

schoolmanagement/academics/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm
from .models import SchoolYear, GradeLevel, Subject


# class InstructorForm(UserCreationForm):
#     title = forms.CharField(max_length=100, required=True)
#     department = forms.CharField(max_length=100, required=True)

#     class Meta:
#         model = User
#         fields = UserCreationForm.Meta.fields + ('title', 'department')

class SchoolYearForm(forms.ModelForm):
    class Meta:
        model = SchoolYear
        fields = '__all__'

class GradeLevelForm(forms.ModelForm):
    class Meta:
        model = GradeLevel
        fields = '__all__'

class SubjectForm(forms.ModelForm):
    class Meta:
        model = Subject
        fields = '__all__'

schoolmanagement/academics/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.models import User
from .forms import SchoolYearForm, GradeLevelForm, SubjectForm
from .models import SchoolYear, GradeLevel, Subject
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate, login, logout


# def add_instructor(request):
#     if request.method == 'POST':
#         instructor_form = InstructorForm(request.POST)
#         if instructor_form.is_valid():
#             user = instructor_form.save()  # Assuming the InstructorForm saves a User instance
#             title = instructor_form.cleaned_data.get('title')
#             department = instructor_form.cleaned_data.get('department')
#             Instructor.objects.create(user=user, title=title, department=department)
#             # Redirect to a new URL:
#             return redirect('academics:academics_index')  # Replace with the name of your list view

#     # if a GET (or any other method) we'll create a blank form
#     else:
#         instructor_form = InstructorForm()

#     context = {
#         'instructor_form': instructor_form,
#         'page_heading': 'Instructor Registration'
#     }
#     print(instructor_form)
#     return render(request, 'academics/add_instructor.html', context)


def academics_index(request):
    return render(request, 'academics/academics_index.html')


# def instructor_login2(request):
#     if request.method == 'POST':
#         form = AuthenticationForm(request, data=request.POST)
#         if form.is_valid():
#             user = form.get_user()
#             login(request, user)
#             # Redirect to a success page.
#             return redirect('academics:academics_index')
#     else:
#         form = AuthenticationForm()
#     return render(request, 'academics/instructors_login.html', {'form': form})


# def instructor_login(request):
#     if request.method == 'POST':
#         form = AuthenticationForm(request, data=request.POST)
#         if form.is_valid():
#             user = form.get_user()
#             login(request, user)
#             # Check if the user is an instructor and redirect accordingly
#             try:
#                 instructor = Instructor.objects.get(user=user)
#                 return redirect('academics:instructor_detail', instructor_id=instructor.pk)
#             except Instructor.DoesNotExist:
#                 # Redirect to a default page if the user is not an instructor
#                 return redirect('students:list_student')
#     else:
#         form = AuthenticationForm()
#     return render(request, 'academics/instructors_login.html', {'form': form})


# def instructor_logout(request):
#     logout(request)
#     # Redirect to the login page (or any other page)
#     return redirect('academics:instructor_login')


# def instructor_detail(request, instructor_id):
#     instructor = get_object_or_404(Instructor, pk=instructor_id)
#     return render(request, 'academics/instructor_detail.html', {'instructor': instructor})

def add_school_year(request):
    if request.method == 'POST':
        form = SchoolYearForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('academics:academics_index')
    else:
        form = SchoolYearForm()
    
    context = {
        'form':form,
    }

    return render(request, 'academics/add_sch_year.html', context)

def view_school_year(request, school_year_id):
    school_year = get_object_or_404(SchoolYear, pk=school_year_id)
    form = SchoolYearForm(instance=school_year)

    
    context = {
        'school_year': school_year,
        'form': form
    }
    
    return render(request, 'academics/view_school_year.html', context)

def list_school_year(request):
    school_years = SchoolYear.objects.all()
    context = {
        'school_years': school_years,
    }
    return render(request, 'academics/list_school_year.html', context)

def add_grade_level(request):
    if request.method == 'POST':
        form = GradeLevelForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('academics:academics_index')
    else:
        form = GradeLevelForm()
    
    context = {
        'form':form,
    }

    return render(request, 'academics/add_grade_level.html', context)

def view_grade_level(request, grade_level_id):
    grade_level = get_object_or_404(GradeLevel, pk=grade_level_id)
    form = GradeLevelForm(instance=grade_level)

    
    context = {
        'grade_level': grade_level,
        'form': form
    }
    
    return render(request, 'academics/view_grade_level.html', context)

def list_grade_levels(request):
    grade_levels = GradeLevel.objects.all()
    context = {
        'grade_levels': grade_levels,
    }
    return render(request, 'academics/list_grade_levels.html', context)

def add_subject(request):
    if request.method == 'POST':
        form = SubjectForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('academics:academics_index')
    else:
        form = SubjectForm()
    
    context = {
        'form':form,
    }

    return render(request, 'academics/add_subject.html', context)

def view_subject(request, subject_id):
    subject = get_object_or_404(Subject, pk=subject_id)
    form = SubjectForm(instance=subject)

    
    context = {
        'subject': subject,
        'form': form
    }
    
    return render(request, 'academics/view_subject.html', context)

def list_subjects(request):
    subjects = Subject.objects.all()
    context = {
        'subjects': subjects,
    }
    return render(request, 'academics/list_subjects.html', context)

schoolmanagement/academics/templates/academics/academics_index.html
{% extends 'webutil/index.html' %}

{% block content %}

<h1>
    Academics Index
</h1>

{% endblock %}

schoolmanagement/academics/templates/academics/add_grade_level.html
{% extends 'students/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <h2>Add Grade Level</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Add</button>
    </form>

{% endblock %}

schoolmanagement/academics/templates/academics/add_instructor.html
{% extends 'webutil/index.html' %}

{% block content %}

<form method="post">
    {% csrf_token %}
    {{ instructor_form.username }}
    {{ instructor_form.username.errors }}
    {{ instructor_form.password1 }}
    {{ instructor_form.password1.errors }}
    {{ instructor_form.password2 }}
    {{ instructor_form.password2.errors }}
    {{ instructor_form.title }}
    {{ instructor_form.title.errors }}
    {{ instructor_form.department }}
    {{ instructor_form.department.errors }}


    <div class="mt-3 text-center">
        <button type="submit" class="btn btn-primary mb-4 mt-4">Submit</button>
    </div>
</form>

{% endblock %}

schoolmanagement/academics/templates/academics/add_sch_year.html
{% extends 'students/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <h2>Add School Year</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Add</button>
    </form>

{% endblock %}

schoolmanagement/academics/templates/academics/add_subject.html
{% extends 'students/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <h2>Add Subject</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Add</button>
    </form>

{% endblock %}

schoolmanagement/academics/templates/academics/instructor_detail.html
{% extends 'webutil/index.html' %}

{% block content %}
  <h1>Instructor Details</h1>
  <p>Name: {{ instructor.user.get_full_name }}</p>
  <p>Title: {{ instructor.title }}</p>
  <p>Department: {{ instructor.department }}</p>
  <!-- Add more fields as necessary -->

<a href="{% url 'academics:instructor_logout' %}">Log out</a>

{% endblock %}

schoolmanagement/academics/templates/academics/instructors_login.html
{% extends 'webutil/index.html' %}

{% block content %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
</form>
{% endblock %}

schoolmanagement/academics/templates/academics/list_grade_levels.html
{% extends 'students/base.html' %}
{% block content %}
<h2>School Year</h2>

<table>
        <thead>
                <tr>
                        <th>Name</th>
                        <th>School Year</th>
                </tr>
        </thead>
        <tbody>
                {% for grade_level in grade_levels %}
                <tr>
                        <td>
                                <a href="{% url 'academics:view_grade_level' grade_level.id %}">
                                {{grade_level.name}} </a>
                        </td>
                        <td> {{grade_level.school_year}} </td>
                </tr>
                {% endfor %}
        </tbody>
</table>


{% endblock content %}

schoolmanagement/academics/templates/academics/list_school_year.html
{% extends 'students/base.html' %}
{% block content %}
<h2>School Year</h2>

<table>
        <thead>
                <tr>
                        <th>Name</th>
                        <th>Start Date</th>
                        <th>End Date</th>
                </tr>
        </thead>
        <tbody>
                {% for school_year in school_years %}
                <tr>
                        <td>
                                <a href="{% url 'academics:view_school_year' school_year.id %}">
                                {{school_year.name}} </a>
                        </td>
                        <td> {{school_year.start_date}} </td>
                        <td>{{ school_year.end_date }}</td>
                        <td> {{ school_year.is_current }} </td>
                </tr>
                {% endfor %}
        </tbody>
</table>


{% endblock content %}

schoolmanagement/academics/templates/academics/list_subjects.html
{% extends 'students/base.html' %}
{% block content %}
<h2>School Year</h2>

<table>
        <thead>
                <tr>
                        <th>Name</th>
                        <th>Subj Code</th>
                        <th>Grade Level</th>
                        <th>Description</th>
                </tr>
        </thead>
        <tbody>
                {% for subject in subjects %}
                <tr>
                        <td>
                                <a href="{% url 'academics:view_subject' subject.id %}">
                                {{subject.name}} </a>
                        </td>
                        <td> {{subject.code}} </td>
                        <td>{{ subject.grade_level }}</td>
                        <td> {{ subject.description }} </td>
                </tr>
                {% endfor %}
        </tbody>
</table>


{% endblock content %}

schoolmanagement/academics/templates/academics/view_grade_level.html
{% extends 'students/base.html' %}
{% load crispy_forms_tags %}



{% block content %}

{{ form.as_p }}



{% endblock content%}

schoolmanagement/academics/templates/academics/view_school_year.html
{% extends 'students/base.html' %}
{% load crispy_forms_tags %}



{% block content %}

{{ form.as_p }}



{% endblock content%}

schoolmanagement/academics/templates/academics/view_subject.html
{% extends 'students/base.html' %}
{% load crispy_forms_tags %}



{% block content %}

{{ form.as_p }}



{% endblock content%}