schoolmanagement/schoolmanagement/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('students/', include('students.urls')),
    path('webutil/', include('webutil.urls')),
    path('academics/', include('academics.urls')),
    path('enrollment/', include('enrollment.urls')),
    path('instructors/', include('instructors.urls')),
]

schoolmanagement/students/urls.py
from .views import blank, create_student, read_student, update_student, delete_student, list_students
from django.urls import path


app_name = 'students'

urlpatterns = [
    path('', blank, name='students-home'),
    path('create/', create_student, name='create-student'),
    path('read/<int:student_id>/', read_student, name='read-student'),
    path('update/<int:student_id>/', update_student, name='update-student'),
    path('delete/<int:student_id>/', delete_student, name='delete-student'),
    path('lists/', list_students, name='list-students'),

]

schoolmanagement/webutil/urls.py
from django.urls import path
from .views import index

app_name = 'webutil'

urlpatterns = [
    path('', index, name='index-webutil'),

]

schoolmanagement/students/forms.py
from django import forms
from .models import Student, Address, Contact
from crispy_bootstrap5.bootstrap5 import FloatingField
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout


class StudentRegistrationForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = ['first_name', 'middle_name', 'last_name', 'suffix', 'birth_date',
                  'country_of_birth', 'birth_place', 'nationality', 'civil_status',
                  'sex', 'religion', 'mobile_number', 'telephone_number', 'personal_email']
        widgets = {
            'birth_date': forms.DateInput(attrs={'type': 'date', 'class': 'form-control', 'id': 'floatingInput', 'placeholder': 'Birthdate'}),
            'first_name': forms.TextInput(attrs={'class': 'form-control', 'id': 'floatingInput', 'placeholder': 'First Name' }),
            'middle_name': forms.TextInput(attrs={'class': 'form-control','id': 'floatingInput', 'placeholder': 'Middle Name'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control', 'id': 'floatingInput', 'placeholder': 'Last Name'}),
            'suffix': forms.TextInput(attrs={'class': 'form-control','id': 'floatingInput', 'placeholder': 'Suffix'}),
            'country_of_birth': forms.TextInput(attrs={'class': 'form-control','id': 'floatingInput', 'placeholder': 'Country of Birth'}),
            'birth_place': forms.TextInput(attrs={'class': 'form-control', 'id': 'floatingInput', 'placeholder': 'Place of Birth'}),
            'nationality': forms.TextInput(attrs={'class': 'form-control', 'id': 'floatingInput', 'placeholder': 'Nationality'}),
            'civil_status': forms.Select(attrs={'class': 'form-control', 'id': 'floatingInput', 'placeholder': 'Civil Status'}),
            'sex': forms.Select(attrs={'class': 'form-control', 'id': 'floatingInput', 'placeholder': 'Sex'}),
            'religion': forms.TextInput(attrs={'class': 'form-control', 'id': 'floatingInput', 'placeholder': 'Religion'}),
            'mobile_number': forms.TextInput(attrs={'class': 'form-control', 'id': 'floatingInput', 'placeholder': 'Mobile Number'}),
            'telephone_number': forms.TextInput(attrs={'class': 'form-control', 'id': 'floatingInput', 'placeholder': 'Telephone Number'}),
            'personal_email': forms.EmailInput(attrs={'class': 'form-control', 'id': 'floatingInput', 'placeholder': 'Personal Email'}),

        }

    def __init__(self, *args, **kwargs):
        super(StudentRegistrationForm,self).__init__(*args, **kwargs)
        self.fields['first_name'].label = "First Name"
        self.fields['middle_name'].label = "Middle Name"
        self.fields['last_name'].label = "Last Name"
        self.fields['suffix'].label = "Suffix"
        self.fields['country_of_birth'].label = "Country of Birth"
        self.fields['birth_place'].label = "Place of Birth"
        self.fields['nationality'].label = "Nationality"
        self.fields['civil_status'].label = "Civil Status"
        self.fields['religion'].label = "Religion"
        self.fields['mobile_number'].label = "Mobile No."
        self.fields['telephone_number'].label = "Telephone No."
        self.fields['personal_email'].label = "Personal E-mail"
        self.fields['sex'].label = "Sex"
        self.fields['birth_date'].label = "Birthdate"


class ViewStudentDetail(forms.ModelForm):
    class Meta:
        model = Student
        fields = ['first_name', 'middle_name', 'last_name', 'suffix', 'birth_date',
                  'country_of_birth', 'birth_place', 'nationality', 'civil_status',
                  'sex', 'religion', 'mobile_number', 'telephone_number', 'personal_email']
        widgets = {
            'birth_date': forms.DateInput(
                attrs={'type': 'date', 'class': 'form-control', 'id': 'floatingInput', 'placeholder': 'Birthdate', 'disabled': 'disabled'}),
            'first_name': forms.TextInput(
                attrs={'class': 'form-control', 'id': 'floatingInput', 'placeholder': 'First Name', 'disabled': 'disabled'}),
            'middle_name': forms.TextInput(
                attrs={'class': 'form-control', 'id': 'floatingInput', 'placeholder': 'Middle Name', 'disabled': 'disabled'}),
            'last_name': forms.TextInput(
                attrs={'class': 'form-control', 'id': 'floatingInput', 'placeholder': 'Last Name', 'disabled': 'disabled'}),
            'suffix': forms.TextInput(attrs={'class': 'form-control', 'id': 'floatingInput', 'placeholder': 'Suffix', 'disabled': 'disabled'}),
            'country_of_birth': forms.TextInput(
                attrs={'class': 'form-control', 'id': 'floatingInput', 'placeholder': 'Country of Birth', 'disabled': 'disabled'}),
            'birth_place': forms.TextInput(
                attrs={'class': 'form-control', 'id': 'floatingInput', 'placeholder': 'Place of Birth', 'disabled': 'disabled'}),
            'nationality': forms.TextInput(
                attrs={'class': 'form-control', 'id': 'floatingInput', 'placeholder': 'Nationality', 'disabled': 'disabled'}),
            'civil_status': forms.Select(
                attrs={'class': 'form-control', 'id': 'floatingInput', 'placeholder': 'Civil Status', 'disabled': 'disabled'}),
            'sex': forms.Select(
                attrs={'class': 'form-control', 'id': 'floatingInput', 'placeholder': 'Sex', 'disabled': 'disabled'}),
            'religion': forms.TextInput(
                attrs={'class': 'form-control', 'id': 'floatingInput', 'placeholder': 'Religion', 'disabled': 'disabled'}),
            'mobile_number': forms.TextInput(
                attrs={'class': 'form-control', 'id': 'floatingInput', 'placeholder': 'Mobile Number', 'disabled': 'disabled'}),
            'telephone_number': forms.TextInput(
                attrs={'class': 'form-control', 'id': 'floatingInput', 'placeholder': 'Telephone Number', 'disabled': 'disabled'}),
            'personal_email': forms.EmailInput(
                attrs={'class': 'form-control', 'id': 'floatingInput', 'placeholder': 'Personal Email', 'disabled': 'disabled'}),

        }


class EditStudentDetail(forms.ModelForm):
    class Meta:
        model = Student
        fields = ['first_name', 'middle_name', 'last_name', 'suffix', 'birth_date',
                  'country_of_birth', 'birth_place', 'nationality', 'civil_status',
                  'sex', 'religion', 'mobile_number', 'telephone_number', 'personal_email']
        widgets = {
            'birth_date': forms.DateInput(
                attrs={'type': 'date', 'class': 'form-control', 'id': 'floatingInput', 'placeholder': 'Birthdate', }),
            'first_name': forms.TextInput(
                attrs={'class': 'form-control', 'id': 'floatingInput', 'placeholder': 'First Name', }),
            'middle_name': forms.TextInput(
                attrs={'class': 'form-control', 'id': 'floatingInput', 'placeholder': 'Middle Name', }),
            'last_name': forms.TextInput(
                attrs={'class': 'form-control', 'id': 'floatingInput', 'placeholder': 'Last Name', }),
            'suffix': forms.TextInput(attrs={'class': 'form-control', 'id': 'floatingInput', 'placeholder': 'Suffix', }),
            'country_of_birth': forms.TextInput(
                attrs={'class': 'form-control', 'id': 'floatingInput', 'placeholder': 'Country of Birth', }),
            'birth_place': forms.TextInput(
                attrs={'class': 'form-control', 'id': 'floatingInput', 'placeholder': 'Place of Birth', }),
            'nationality': forms.TextInput(
                attrs={'class': 'form-control', 'id': 'floatingInput', 'placeholder': 'Nationality', }),
            'civil_status': forms.Select(
                attrs={'class': 'form-control', 'id': 'floatingInput', 'placeholder': 'Civil Status', }),
            'sex': forms.Select(
                attrs={'class': 'form-control', 'id': 'floatingInput', 'placeholder': 'Sex', }),
            'religion': forms.TextInput(
                attrs={'class': 'form-control', 'id': 'floatingInput', 'placeholder': 'Religion', }),
            'mobile_number': forms.TextInput(
                attrs={'class': 'form-control', 'id': 'floatingInput', 'placeholder': 'Mobile Number', }),
            'telephone_number': forms.TextInput(
                attrs={'class': 'form-control', 'id': 'floatingInput', 'placeholder': 'Telephone Number', }),
            'personal_email': forms.EmailInput(
                attrs={'class': 'form-control', 'id': 'floatingInput', 'placeholder': 'Personal Email', }),

        }


class ViewAddressDetail(forms.ModelForm):
    class Meta:
        model = Address
        fields = ['province', 'city', 'house_number', 'barangay', 'postal_code']

        widgets = {
            'province': forms.TextInput(attrs={'class': 'form-control', 'disabled': 'disabled', 'id': 'floatingInput', 'placeholder': 'Province', }),
            'city': forms.TextInput(attrs={'class': 'form-control', 'disabled': 'disabled'}),
            'house_number': forms.TextInput(attrs={'class': 'form-control', 'disabled': 'disabled'}),
            'barangay': forms.TextInput(attrs={'class': 'form-control', 'disabled': 'disabled'}),
            'postal_code': forms.TextInput(attrs={'class': 'form-control', 'disabled': 'disabled'}),
        }


class AddressForm(forms.ModelForm):
    class Meta:
        model = Address
        fields = ['province', 'city', 'house_number', 'barangay', 'postal_code']

        widgets = {
            'province': forms.TextInput(attrs={'class': 'form-control', 'id': 'floatingInput', 'placeholder': 'Province'}),
            'city': forms.TextInput(attrs={'class': 'form-control', 'id': 'floatingInput', 'placeholder': 'City'}),
            'house_number': forms.TextInput(attrs={'class': 'form-control', 'id': 'floatingInput', 'placeholder': 'House Number'}),
            'barangay': forms.TextInput(attrs={'class': 'form-control', 'id': 'floatingInput', 'placeholder': 'Barangay'}),

schoolmanagement/students/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import StudentRegistrationForm, AddressForm, ContactForm, \
    ViewAddressDetail, ViewContactDetail, ViewStudentDetail, \
    EditStudentDetail, EditAddressDetail, EditContactDetail

from django.contrib import messages
from django.db import transaction
from .models import Student, Contact, Address
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


def blank(requests):
    context = {'page_heading': 'Blank Page Heading'}
    return render(requests, 'students/blank.html', context)


def read_student(request, student_id):
    student = get_object_or_404(Student, pk=student_id)

    # Assuming a OneToOne relationship with Address
    address = Address.objects.filter(student=student).first()
    address_form = ViewAddressDetail(instance=address)

    # Assuming a ForeignKey relationship with Contact (fetching all related contacts)
    contacts = Contact.objects.filter(student=student)
    contact_form = [ViewContactDetail(instance=contact) for contact in contacts]

    context = {
        'student_form': ViewStudentDetail(instance=student),
        'address_form': address_form,
        'contact_form': contact_form,
        'student_id': student_id,
        'page_heading': 'Student Detail'
    }
    return render(request, 'students/read-student.html', context)


def create_student(request):
    if request.method == 'POST':
        student_form = StudentRegistrationForm(request.POST)
        address_form = AddressForm(request.POST)
        contact_form = ContactForm(request.POST)

        if student_form.is_valid() and address_form.is_valid() and contact_form.is_valid():
            with transaction.atomic():
                student = student_form.save()

                # Save address information
                address = address_form.save(commit=False)
                address.student = student
                address.save()

                # Save contact information
                contact = contact_form.save(commit=False)
                contact.student = student
                contact.save()

                messages.success(request, 'Student information saved successfully!')
                return redirect('students:students-home')
        else:
            # Handle form errors
            for form in [student_form, address_form, contact_form]:
                for error in form.errors.values():
                    messages.error(request, error)
    else:
        student_form = StudentRegistrationForm()
        address_form = AddressForm()
        contact_form = ContactForm()

    context = {
        'student_form': student_form,
        'address_form': address_form,
        'contact_form': contact_form,
        'page_heading': 'Student Registration'
    }
    return render(request, 'students/create-student.html', context)


def update_student(request, student_id):
    student = get_object_or_404(Student, pk=student_id)
    address = Address.objects.filter(student=student).first()
    contacts = Contact.objects.filter(student=student)

    if request.method == 'POST':
        student_form = EditStudentDetail(request.POST, instance=student)
        address_form = EditAddressDetail(request.POST, instance=address)
        contact_forms = [EditContactDetail(request.POST, instance=contact) for contact in contacts]

        if (student_form.is_valid() and address_form.is_valid()
                and all(cf.is_valid() for cf in contact_forms)):
            student_form.save()
            address_form.save()
            for cf in contact_forms:
                cf.save()
            messages.success(request, 'Student details updated successfully!')
            return redirect('students:students-home')
        else:
            # Print form errors to the console
            print("Student Form Errors:", student_form.errors)
            print("Address Form Errors:", address_form.errors)
            for cf in contact_forms:
                print("Contact Form Errors:", cf.errors)

    else:
        student_form = StudentRegistrationForm(instance=student)
        address_form = AddressForm(instance=address)
        contact_forms = [ContactForm(instance=contact) for contact in contacts]

    return render(request, 'students/update-student.html', {
        'student_form': student_form,
        'address_form': address_form,
        'contact_form': contact_forms,
        'student_id': student_id,
    })


def delete_student(request, student_id):
    student = get_object_or_404(Student, pk=student_id)
    student.delete()
    messages.success(request, 'Student record deleted successfully!')
    return HttpResponseRedirect(reverse('students:students-home'))


def list_students(request):
    students = Student.objects.all()
    for student in students:
        print(student.first_name)
    context = {
        'students': students,
        'page_heading': 'Student List',
    }
    return render(request, 'students/list-students.html', context)

schoolmanagement/students/templates/students/blank.html
{% extends 'students/base.html' %}

{% block title %}

<h3>Blank Page Content Sample</h3>

{% endblock %}

schoolmanagement/students/templates/students/list-students.html
{% extends 'students/base.html' %}

{% load crispy_forms_tags %}

{% block content %}

          <div class="card shadow mb-4">
            <div class="card-header py-3">
              <h6 class="m-0 font-weight-bold text-primary">Students List</h6>
            </div>
            <div class="card-body">
              <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                  <thead>
                    <tr>
                      <th>School ID</th>
                      <th>First Name</th>
                      <th>Middle Name</th>
                      <th>Last Name</th>
                      <th>Personal Email</th>
                    </tr>
                  </thead>
                  <tbody>
                        {% for student in students %}
                            <tr>
                                <td>
                                    <a href="{% url 'students:read-student' student.id %}" >
                                      {{ student.std_sch_id }} </a>
                                </td>
                                <td>{{ student.first_name }}</td>
                                <td>{{ student.middle_name }}</td>
                                <td>{{ student.last_name }}</td>
                                <td>{{ student.personal_email }}</td>
                            </tr>
                        {% endfor %}

                  </tbody>
                </table>
              </div>
            </div>
          </div>
{% endblock %}

schoolmanagement/students/templates/students/read-student.html
{% extends 'students/base.html' %}
{% load crispy_forms_tags %}



{% block content %}

<form method="post">
    {% csrf_token %}

    <!-- Basic Details Section -->
    <div class="card mb-4">
        <div class="card-header text-center">
            <h4>Basic Details</h4>
        </div>
        <div class="card-body">
            <div class="row">
                                    <div class="col-3 mt-3">

                                            <div class="form-floating">

                                                {{ student_form.first_name }}
                                                <label for="{{ student_form.first_name.id_for_label }}" >{{ student_form.first_name.label }}</label>
                                                {{ student_form.first_name.errors }}

                                            </div>

                                    </div>
                                    <div class="col-3 mt-3">
                                            <div class="form-floating">
                                                {{ student_form.middle_name }}
                                                <label for="{{ student_form.middle_name.id_for_label }}">{{ student_form.middle_name.label }}</label>
                                                {{ student_form.middle_name.errors }}
                                            </div>
                                    </div>
                                    <div class="col-3 mt-3">
                                            <div class="form-floating">
                                                {{ student_form.last_name }}
                                                <label for="{{ student_form.last_name.id_for_label }}">{{ student_form.last_name.label }}</label>
                                                {{ student_form.last_name.errors }}
                                            </div>
                                    </div>
                                    <div class="col-3 mt-3">
                                            <div class="form-floating">
                                                {{ student_form.suffix }}
                                                <label for="{{ student_form.suffix.id_for_label }}">{{ student_form.suffix.label }}</label>
                                                {{ student_form.suffix.errors }}
                                            </div>
                                    </div>
            </div>

            <div class="row" >
                                    <div class="col-3 mt-3">
                                            <div class="form-floating">
                                                {{ student_form.birth_place }}
                                                <label for="{{ student_form.birth_place.id_for_label }}">{{ student_form.birth_place.label }}</label>
                                                {{ student_form.birth_place.errors }}
                                            </div>
                                    </div>

                                    <div class="col-3 mt-3">
                                            <div class="form-floating">
                                                {{ student_form.country_of_birth }}
                                                <label for="{{ student_form.country_of_birth.id_for_label }}">{{ student_form.country_of_birth.label }}</label>
                                                {{ student_form.country_of_birth.errors }}
                                            </div>
                                    </div>
                                    <div class="col-3 mt-3">
                                            <div class="form-floating">
                                                {{ student_form.nationality }}
                                                <label for="{{ student_form.nationality.id_for_label }}">{{ student_form.nationality.label }}</label>
                                                {{ student_form.nationality.errors }}
                                            </div>
                                    </div>

                                    <div class="col-3 mt-3">
                                            <div class="form-floating">
                                                {{ student_form.birth_date }}
                                                <label for="{{ student_form.birth_date.id_for_label }}">{{ student_form.birth_date.label }}</label>
                                                {{ student_form.birth_date.errors }}
                                            </div>
                                    </div>
            </div>
            <div class="row">
                                    <div class="col-3 mt-3">
                                            <div class="form-floating">
                                                {{ student_form.civil_status }}
                                                <label for="{{ student_form.civil_status.id_for_label }}">{{ student_form.civil_status.label }}</label>
                                                {{ student_form.civil_status.errors }}
                                            </div>
                                    </div>
                                    <div class="col-3 mt-3">
                                            <div class="form-floating">
                                                {{ student_form.sex }}
                                                <label for="{{ student_form.sex.id_for_label }}">{{ student_form.sex.label }}</label>
                                                {{ student_form.sex.errors }}
                                            </div>
                                    </div>
                                    <div class="col-3 mt-3">
                                            <div class="form-floating">
                                                {{ student_form.religion }}
                                                <label for="{{ student_form.religion.id_for_label }}">{{ student_form.religion.label }}</label>
                                                {{ student_form.religion.errors }}
                                            </div>
                                    </div>
            </div>
            <div class="row">
                                    <div class="col-3 mt-3">
                                            <div class="form-floating">
                                                {{ student_form.mobile_number }}
                                                <label for="{{ student_form.mobile_number.id_for_label }}">{{ student_form.mobile_number.label }}</label>
                                                {{ student_form.mobile_number.errors }}
                                            </div>
                                    </div>
                                    <div class="col-3 mt-3">
                                            <div class="form-floating">
                                                {{ student_form.telephone_number }}
                                                <label for="{{ student_form.telephone_number.id_for_label }}">{{ student_form.telephone_number.label }}</label>
                                                {{ student_form.telephone_number.errors }}
                                            </div>
                                    </div>
                                    <div class="col-3 mt-3">
                                            <div class="form-floating">
                                                {{ student_form.personal_email }}
                                                <label for="{{ student_form.personal_email.id_for_label }}">{{ student_form.personal_email.label }}</label>
                                                {{ student_form.personal_email.errors }}
                                            </div>
                                    </div>

            </div>

        </div>
    </div>

    <!-- Address Section -->
    <div class="card mb-4">
        <div class="card-header text-center">
            <h4>Address</h4>
        </div>
        <div class="card-body">
                                <div class="row">

                                        <div class="col-3 mt-3">

                                                <div class="form-floating">

                                                    {{ address_form.province }}
                                                    <label for="{{ address_form.province.id_for_label }}" >{{ address_form.province.label }}</label>
                                                    {{ address_form.province.errors }}

                                                </div>

                                        </div>

                                        <div class="col-3 mt-3">

                                                <div class="form-floating">

                                                    {{ address_form.city }}
                                                    <label for="{{ address_form.city.id_for_label }}" >{{ address_form.city.label }}</label>
                                                    {{ address_form.city.errors }}

                                                </div>

                                        </div>                                        

                                        <div class="col-3 mt-3">

                                            <div class="form-floating">

                                                {{ address_form.house_number }}
                                                <label for="{{ address_form.house_number.id_for_label }}" >{{ address_form.house_number.label }}</label>
                                                {{ address_form.house_number.errors }}

                                            </div>

                                        </div>    

                                        <div class="col-3 mt-3">

                                            <div class="form-floating">

                                                {{ address_form.barangay }}
                                                <label for="{{ address_form.barangay.id_for_label }}" >{{ address_form.barangay.label }}</label>
                                                {{ address_form.barangay.errors }}

                                            </div>

                                        </div>


                                </div>
                                <div class="row">
                                    
                                    <div class="col-3 mt-3">

                                        <div class="form-floating">

                                            {{ address_form.postal_code }}
                                            <label for="{{ address_form.postal_code.id_for_label }}" >{{ address_form.postal_code.label }}</label>
                                            {{ address_form.postal_code.errors }}

                                        </div>

                                    </div>

                                </div>
        </div>
    </div>

<div class="card mb-4">
    <div class="card-header text-center">
      <h4>Contact in Case of Emergency</h4>
    </div>
    <div class="card-body">
{% for contact_form in contact_form %}
      <!-- Display the fields for each contact form here -->
      <div class="row justify-content-center">  

                                    <div class="col-4 mt-3">
                                        <div class="form-floating">
                                            {{ contact_form.full_name }}
                                            <label for="{{ contact_form.full_name.id_for_label }}" >{{ contact_form.full_name.label }}</label>
                                            {{ contact_form.full_name.errors }}
                                        </div>
                                    </div>

                                    <div class="col-4 mt-3">
                                        <div class="form-floating">
                                            {{ contact_form.relationship }}
                                            <label for="{{ contact_form.relationship.id_for_label }}" >{{ contact_form.relationship.label }}</label>
                                            {{ contact_form.relationship.errors }}
                                        </div>
                                    </div>

                                    <div class="col-4 mt-3">
                                        <div class="form-floating">
                                            {{ contact_form.mobile_number }}
                                            <label for="{{ contact_form.mobile_number.id_for_label }}" >{{ contact_form.mobile_number.label }}</label>
                                            {{ contact_form.mobile_number.errors }}
                                        </div>
                                    </div>

      </div>

{% endfor %}
        <div class="container">
            <div class="text-center">
                <a href="{% url 'students:update-student' student_id=student_form.instance.id %}" class="btn btn-secondary">Edit</a>
            </div>
        </div>



    </div>
</div>


</form>
{% endblock %}